version: '1.0.0'

services:
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: always
    ports: 
      - "80:8080"
    volumes:
      - ${PWD}/swagger.yml:/swagger.yml
    environment: 
      - SWAGGER_JSON=/swagger.yml
  redoc:
    container_name: redoc
    image: redocly/redoc
    ports: 
      - "8080:80"
    environment:
      - SPEC_URL=http://localhost:80/swagger.yml